### PR TITLE
Yiliu/master/add featured story

### PR DESCRIPTION
**Pull request by flora8984461**
update the theme to add the featured story, but need to fix missing of newsletter and announcements

Signed-off-by: Yi Liu <yi.liu@eclipse-foundation.org>

### CODE REVIEW

**Comment by flora8984461** [comment]
There is a style 
```
.featured-ad a, .featured-side a {
    float: right; 
}
```
causing the icon and button not align correctly

image

**Comment by chrisguindon** [comment]
@flora8984461 

We can fix this by updating the classname here https://github.com/EclipseFdn/opengenesis.eclipse.org/blob/master/less/styles.less#L25

**Review by chrisguindon — CHANGES_REQUESTED** [review]
The Sign up to our Mailing list section is also missing

**Review by chrisguindon — CHANGES_REQUESTED** [review]
The featured story is showing in footer. This will require a patch to our base theme.

**Pull request merged**
